### ISSUE TITLE
Very slow performance on mobile

### ISSUE THREAD

**Issue by Androz2091** [gildas-lormeau/zip.js#221] opened 2021-02-20 11:53 UTC
Hello,
First, thank you for this library, it's very useful. I used it because it has better performances than JSZip, but on mobile devices it takes ~300ms (Huawei PSmart 2020) to read a file read in 10ms on a computer (MacOS Mini M1 2020). Can something be done to improve that?
Thanks

**Comment by gildas-lormeau** [comment] 2021-02-20 13:24
What kind of `Reader`do you use to read the zip file? If you're using the `BlobReader` class, maybe you could try the `Uint8ArrayReader` class instead. There are good chances it will be faster. Also, did you try to disable web workers to see if it helps?

**Comment by gildas-lormeau** [comment] 2021-02-20 15:09
I think I need more details actually. How large is the file you're trying to read? Do you know if it's the call to `ZipReader#getEntries` or `Entry#getData` that takes time?

**Comment by Androz2091** [comment] 2021-02-20 16:31
@gildas-lormeau here is my file: https://github.com/Androz2091/discord-data-package-explorer/blob/mobile-perf-improvmnts/src/app/extractor.js#L84

On my computer it shows 10ms, and it shows 300ms on mobile

**Comment by Androz2091** [comment] 2021-02-21 21:53
I switched to jszip (https://github.com/Androz2091/discord-data-package-explorer/commit/9a4ebc6c11c4db0575a10a51b5d813b42baa71b3) and it takes 10 sec instead of 45 sec with zip.js... I'm still available by email if you need more info

**Comment by gildas-lormeau** [comment] 2021-02-21 22:04
Ok... Thanks for the info

**Comment by gildas-lormeau** [comment] 2021-02-22 00:56
BTW, It would have been great and useful if you had followed my advises.

**Comment by gildas-lormeau** [comment] 2021-02-24 00:47
Note that I would have helped you if you had answered at least one of my questions. Otherwise, you must provide a simple test showing the problem if you you want me to see what's wrong.

**Comment by Androz2091** [comment] 2021-02-24 08:39
> How large is the file you're trying to read?

300mb, and I'm reading around 900 files in a directory of this zip file

> Also, did you try to disable web workers to see if it helps?

Yes. I also tried pako. It didn't help...

> Do you know if it's the call to ZipReader#getEntries or Entry#getData that takes time?

Yes, it is `Entry#getData`

**Comment by gildas-lormeau** [comment] 2021-02-24 11:18
Thank you for the additional info, I'll try to write a test to see if I can improve things.  There are 2 other parameters that could be tweaked (via `zip.configure`):
 - `maxWorkers` could be reduced to `2` or `1` maybe. That would make the code less "CPU aggressive"
 - `maxChunk` is the size of the chunks sent to the web worker, by default it's 512 * 1024 (512K). Maybe increasing it to 1MB or 2MB could help.

**Comment by gildas-lormeau** [comment] 2021-02-24 14:05
@Androz2091 I wrote a test and I cannot reproduce your issue.

Here is the link of the test: https://jsfiddle.net/bmjd2wyv/2/

The script creates first a zip file with 900 random entries. The zip file weights ~ 300MB. Then, it reads all the entries and displays the time it took in the HTML. With a Pixel 3a, it takes ~ 8000ms to read them all in Chrome.

**Comment by gildas-lormeau** [comment] 2021-02-24 14:33
I'm getting old I guess, the generated file weights 300KB. I'm fixing that...

**Comment by gildas-lormeau** [comment] 2021-02-24 15:13
@Androz2091 Here the correct test: https://jsfiddle.net/9aj0p8cL/1/

I get a result of ~10,000 ms on the Pixel 3a. Beware, the creation of the zip file may takes one minute or more.

**Comment by gildas-lormeau** [comment] 2021-02-25 08:14
Out of curiosity, what result do you get on your phone for the same test @Androz2091?

**Comment by Androz2091** [comment] 2021-02-25 08:19
Thank you for your answers, I will be back at home in 10 hours and I will be able to try everything!

**Comment by gildas-lormeau** [comment] 2021-02-25 11:52
Sure no problem!

**Comment by Androz2091** [comment] 2021-02-26 08:09
I'm getting the following error on the jsfiddle on my computer:
```js
<a class='gotoLine' href='#[object DOMException'>[object DOMException</a> {
  ABORT_ERR: 20,
  code: 18,
  DATA_CLONE_ERR: 25,
  DOMSTRING_SIZE_ERR: 2,
  HIERARCHY_REQUEST_ERR: 3,
  INDEX_SIZE_ERR: 1,
  INUSE_ATTRIBUTE_ERR: 10,
  INVALID_ACCESS_ERR: 15,
  INVALID_CHARACTER_ERR: 5,
  INVALID_MODIFICATION_ERR: 13,
  INVALID_NODE_TYPE_ERR: 24,
  INVALID_STATE_ERR: 11,
  message: "Failed to construct 'Worker': Access to the script at 'blob:https://fiddle.jshell.net/f110d243-7b34-4fdb-a1f5-e458fdf4f6ca' is denied by the document's Content Security Policy.",
  name: "SecurityError",
  NAMESPACE_ERR: 14,
  NETWORK_ERR: 19,
  NO_DATA_ALLOWED_ERR: 6,
  NO_MODIFICATION_ALLOWED_ERR: 7,
  NOT_FOUND_ERR: 8,
  NOT_SUPPORTED_ERR: 9,
  QUOTA_EXCEEDED_ERR: 22,
  SECURITY_ERR: 18,
  stack: "Error: Failed to construct 'Worker': Access to the script at 'blob:https://fiddle.jshell.net/f110d243-7b34-4fdb-a1f5-e458fdf4f6ca' is denied by the document's Content Security Policy.
    at https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:13735
    at Ct (https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:14749)
    at Mt (https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:15332)
    at https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:73969
    at Object.assign.rawFilename (https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:74879)
    at async t.ZipWriter.add (https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.2.17/dist/zip.min.js:1:72477)
    at async Promise.all (index 0)
    at async test (https://fiddle.jshell.net/9aj0p8cL/1/show/?editor_console=:133:2)",
  SYNTAX_ERR: 12,
  TIMEOUT_ERR: 23,
  TYPE_MISMATCH_ERR: 17,
  URL_MISMATCH_ERR: 21,
  VALIDATION_ERR: 16,
  WRONG_DOCUMENT_ERR: 4
}]
```

On my phone, the zip is read in 11575ms. I will try to investigate with my own zip file

**Comment by gildas-lormeau** [comment] 2021-02-26 09:40
Thank you for the feedback. JSFiddle seems to block scripts loaded with a Blob URI in certain circumstances. This could be fixed by using the `z-worker.js` file if necessay.

**Comment by gildas-lormeau** [comment] 2021-02-28 14:11
In the meantime, it might be nice if you didn't say on the README page of your project that zip.js is much slower. The test I wrote proves that this is not true, at least in general.

**Comment by Androz2091** [comment] 2021-02-28 14:18
Yes sure, I totally understand sorry 👍 
I removed it, and will make the tests as soon as possible :wink:

**Comment by gildas-lormeau** [comment] 2021-04-10 10:20
I'm closing this issue since it's quite obvious you won't make any tests.

**Closed by gildas-lormeau** 2021-04-10 10:20 UTC
Labels: cannot be reproduced
