### ISSUE TITLE
Webdriverio broken since the latest push

### ISSUE THREAD

**Issue by Betusto** [gildas-lormeau/zip.js#520] opened 2024-07-17 22:59 UTC
Webdriverio installs by default the latest version of @zip.js/zip.js, so it is installing 2.7.46, but this is preventing our automations tests to run with this newest version, it says:

"ReferenceError: Blob is not defined" every time we want to run our tests by using the command "npm run wdio", would you take a look please?

The error is happening from today July 17th 2024.

**Comment by gildas-lormeau** [comment] 2024-07-18 08:42
That's strange. The changes I made in the version `2.7.46` should not affect you. Do you have more details about this error?

**Comment by Merano01** [comment] 2024-07-18 09:22
we have similar problems since today; part of the stacktrace - in case that helps

ReferenceError: Blob is not defined
    at e (file:///<snip>/uitestframework/wdio/node_modules/@zip.js/zip.js/lib/z-worker-inline.js:1:45675)
    at file:///<snip>/uitestframework/wdio/node_modules/@zip.js/zip.js/lib/zip-fs.js:42:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async file:///<snip>/uitestframework/wdio/node_modules/@wdio/cli/bin/wdio.js:15:17

**Comment by gildas-lormeau** [comment] 2024-07-18 10:33
Thank you for the info, I think I was able to find the cause of the regression. Could you tell me if the version `2.7.47` that I've just published fixes the issue?

**Comment by Merano01** [comment] 2024-07-18 10:51
our tests are not very verbose, if everything works fine (can't see zip.js the version), but everything is running fine again; so I am very confident, that your fix did it

$ cd wdio/
$ node node_modules/@wdio/cli/bin/wdio.js wdio.ci.smoketest.conf.ts --baseUrl $BASE_URL
Execution of 73 workers started at 2024-07-18T10:44:35.958Z
[0-1] RUNNING in chrome - file:///tests/features/admin/evaluations/evaluations-check.feature

**Comment by clss1** [comment] 2024-07-18 10:54
I can confirm as well that it works again. Thank you very much for the quick fix!

**Comment by gildas-lormeau** [comment] 2024-07-18 11:28
Thank you very much for the feedback @Merano01 ans @clss1! I'm closing the issue.

**Closed by gildas-lormeau** 2024-07-18 11:28 UTC
