### ISSUE TITLE
Incomplete zip file when compress a big number of files. (+100)

### ISSUE THREAD

**Issue by MedimSight** [gildas-lormeau/zip.js#52] opened 2013-05-13 13:48 UTC
Hi, I'm using a code similar to the example of multiple blob zipping.

```Javascript
function zipFiles(files, x, y, nFile, sdata) {
    zip.createWriter(new zip.BlobWriter("application/zip"), function(zipWriter) {
        var addIndex = 1;
	function nextFile() {
	    if (addIndex < TableFiles[x][y].length) {
	        zipWriter.add(files[TableFiles[x][y][addIndex]].name, new zip.BlobReader(files[DicomPatientsFiles[x][y][addIndex]]), function() {
		    addIndex++;
		    nextFile();
		}, function(current, total) {});
	    } else {
	        zipWriter.close(function(blob) {
	    	    reader = new FileReader(); 
	    	    reader.onload = function(evt) {
	    	        console.log('Test blob file ' + nFile + ': ' + evt.target.result) 
	            }; 
	    	    reader.readAsText(blob.slice(blob.size - 100,blob.size - 1)); // [1]
	    	    Zipping -= 1;
		    uploadZipBlob(nFile, blob, sdata[4]+'.zip', sdata);
              } );				
	   }		
       }
       nextFile();
    }, onerror);
};
		
zipFiles(files, x, y, nFile, sdata);
```
The problem always happens even using the same groups of files. When the "Test Blob" log show data por that range [1], effectively, the zip is correct. In other cases, the blob look as incomplete and just contains a part (Each time with a different file size.) of the total zip file. The Blob.size always is correct. Maybe a problem with Chrome or with my code, but I can't find the final problem.

**Comment by Rob--W** [comment] 2015-05-16 12:12
This issue is a duplicate of #80, which has been resolved because the upstream Chrome bug has been fixed (https://github.com/gildas-lormeau/zip.js/issues/80#issuecomment-102620847).

**Closed by Rob--W** 2015-05-16 12:12 UTC
