### ISSUE TITLE
Incorrect values sent to onprogress for getFileEntry

### ISSUE THREAD

**Issue by gregpsycle** [gildas-lormeau/zip.js#41] opened 2013-03-07 16:08 UTC
I have a zipfs into which I've imported a blob. I'm using getFileEntry to then extract the zip to an HTML5 filesystem inside a Chrome app. This all works fine.
The onprogress callback though, is getting 'index' (first argument) values that fluctuate (i.e. don't always get bigger), and aren't always smaller than 'max size' (second argument). Max-size is correct.

I think the fix is to change line 236 in zip-fs.js from:

onprogress(currentIndex + index, totalSize);

to just:

onprogress(currentIndex, totalSize);

but I might be misunderstanding what this is meant to be doing.

**Comment by danielweck** [comment] 2015-10-10 20:40
@gregpsycle removing ` + index` works for me too.
Note that `onprogress(currentIndex + index, totalSize);` is wrong for the export function too (in the same file `zip-fs.js`)

**Comment by Rob--W** [comment] 2015-10-11 10:50
@danielweck  / @gregpsycle Patches are welcome ;)

**Comment by gildas-lormeau** [comment] 2021-01-12 10:47
I was able to reproduce the issue, it should be fixed now.

**Closed by gildas-lormeau** 2021-01-12 10:47 UTC

**Comment by danielweck** [comment] 2021-01-12 11:19
2013 ... how time passes :)

**Comment by gildas-lormeau** [comment] 2021-01-12 11:32
You bet! :)
