### ISSUE TITLE
Doesn't respect zip format

### ISSUE THREAD

**Issue by greggman** [gildas-lormeau/zip.js#148] opened 2016-06-13 10:21 UTC
Here's a valid zip file. It has 2 central directories. According to the zip spec only the last directory is valid. The first should be ignored but zip.js only sees the first one (the one that should be ignored)

[abcdef.zip](https://github.com/gildas-lormeau/zip.js/files/311604/abcdef.zip)

**Comment by duanyao** [comment] 2016-06-20 02:58
If I read the spec correctly, it doesn't say that "the last central directory is valid if there are more than one", rather, it says that the offset of the *central directory* is stored in the *end of central directory record* and there must be only one *end of central directory record* in a zip file. The spec also doesn't say that there must be no gap between the *central directory* and the *end of central directory record* -- though it also doesn't say there can be a gap.

In the test case you provided, the first *central directory*'s offset (275) is stored in the *end of central directory record* (offset 1098), but the second *central directory*(offset 835) is placed just before the *end of central directory record*. So I think technically zip.js behaves correctly.

However, most zip tools I tested (unzip in linux, minizip in zlib, and jszip) do regard the second *central directory* as the valid one. Why? I found the answer in jszip's [comment](https://github.com/Stuk/jszip/blob/cb28f5ec09986861eaedfbfd132b60b9139a6c39/lib/zipEntries.js#L239) (you can debug jszip with your test case [here](http://stuk.github.io/jszip/documentation/examples/read-local-file-api.html)):

>the offset is wrong, update the "zero" of the reader
>this happens if data has been prepended (crx files for example)

So basicly this is a rescure for incorrectly prepended zip files. The offsets in such files are all wrong, and those zip tools try to guess the amount of prepended data by assuming that there is no gap between *central directory* and the *end of central directory record*.

@Rob--W do you think we should fix this?

**Comment by greggman** [comment] 2016-06-20 07:14
no this is not a rescue for insecurely prepended zip files.

Think of this case. Files inside a zip file can be stored uncompressed. So if you zip a zip file you'll have 2 headers at the end of the file. The header for the inner zip and the header for the outer zip. If you don't only use the last header you'll incorrectly unzip.

As for the actual spec. The spec is specifically that the last header is the only valid header. The format was designed for you to be able to append files by reading the header at the end of the zip, adding more files and appending a new header. This is because the format was designed back in floppy disk days. Imagine you had an zip that spanned 5 disks. Now imagine you just want to update a single small file inside that zip. Without this ability to append you'd need another 5 disks. It would first ask you to put in the last disk so it can read the header. Then it would ask you to put in the first disk so it can copy all the entries into memory, put in an unused disk to copy everything over, continue for 5 disks, finally it would add the file you asked and write a new header.  But, because zip specifically only reads the last header instead it just tells you to put in the last disk, it reads the header, appends the new data, writes a a new header. Only one disk is involved, the last disk. Where as without this ability to append a header you'd have 10 disks involved.

**Comment by duanyao** [comment] 2016-06-20 08:40
In the case of zip in another zip file, only the last central directory is valid because only the last end of central directory record is valid and is pointing at it. Current zip.js can handle it correctly.

Can you point out the specific sentences of the spec to support your point? If there can not be a gap between *central directory* and the *end of central directory record*, then the field *offset of start of central  directory with respect to the starting disk number* (section 4.3.16) in the latter is redundant. If zip tools should respect *offset of start of central  directory with respect to the starting disk number*, there is nothing prevent a valid *central directory* being placed anywhere in a zip file (execpt at the end of file). Sure the *central directory* is usually placed near the end of zip file to enable *append*-only modification, but I don't see the spec explictly forbid otherwise.

Also note that your test case is regarded as *prepened* (not appended!) by most zip tools, and is obviously not a well-formed zip file.

**Comment by greggman** [comment] 2016-06-20 08:56
I didn't come here to argue. All the zip tools I use correctly unzip the
file above. Your library does not. Other libraries do.

If you don't consider that a bug feel free to close this ticket

**Comment by murkle** [comment] 2016-06-20 09:10
When opening abcdef.zip
* Windows Explorer shows folder **abc**
* 7-zip shows folder **abc**
* WinRAR shows folder **def**

**Comment by duanyao** [comment] 2016-06-20 09:11
This is my test result of multiple zip tools, *A* is picking the first central directory, *B* is picking the second:

A: zip.js, 7zip 15 for Windows, WinZip 20, Window 10 Explorer.

B: jszip, unzip for linux, zlib minizip, jar in JDK.

It seems zip.js is not the only one.

**Comment by Rob--W** [comment] 2016-06-21 10:08
According to the above comment, the zip file is not well-formed. There are two implementations, both being used by popular tools, so there seems to not be an agreed-upon way to deal with it among the popular tools. Hence I suggest to not change the behavior, for backwards-compatibility with old zip.js versions.

If you can demonstrate that this issue is not specific to this "contrived" example (e.g. there are popular tools that generate such a "faulty" zip file), then I'd be receptive to a PR that adds a configuration option that allows you to choose one behavior over the other (defaulting to the current state).

**Comment by gildas-lormeau** [comment] 2021-01-14 12:11
I'm closing this issue because I cannot reproduce it with the latest version. I guess it was fixed meanwhile.

**Closed by gildas-lormeau** 2021-01-14 12:11 UTC
