### ISSUE TITLE
Stop zip creation

### ISSUE THREAD

**Issue by rdo182** [gildas-lormeau/zip.js#193] opened 2019-03-02 20:36 UTC
Hi guys!

I'm with a little problem, i want that the user can stop the creation of the zip, but searching here for something like these: Stop zip creation, Cancel zip creation, Stop or Cancel. Didn't find anything.

There is some way to do that?

**Comment by gildas-lormeau** [comment] 2021-01-12 02:25
duplicate of #69

**Closed by gildas-lormeau** 2021-01-12 02:25 UTC
