### ISSUE TITLE
Unexpected "Extra bytes past the end" error when decompressing data in Safari 16.4

### ISSUE THREAD

**Issue by Rajek88** [gildas-lormeau/zip.js#412] opened 2023-05-04 06:29 UTC
Hi, I would like to report an issue,
On Safari 16.3, and all other latest browsers, everything worked perfectly fine, 
But on Safari 16.4, it started me giving the error 
"
[Error] Unhandled Promise Rejection: TypeError: Extra bytes past the end.
	pipeToFinalize
	(anonymous function)
" 
When I try to download and extract a zip from the internet, And yes the zip I am trying to use is not corrupt or incomplete, It was working fine with Safari 16.3,

Any help is appreciated, Thanks

**Comment by gildas-lormeau** [comment] 2023-05-04 10:00
You should report this bug to Apple. Are you sure you're using the stable version of Safari?

**Comment by Rajek88** [comment] 2023-05-04 10:55
Yes, It's a stable version of Safari,
When I checked the network calls, the issue was shown as emerged from
zip-full.fs.js

Attaching the screenshot of place where issue is arising from.

**Comment by gildas-lormeau** [comment] 2023-05-04 11:03
Please upload the screenshot though the GitHub user interface. Attached files in mail don't work on GitHub.

**Comment by Rajek88** [comment] 2023-05-04 11:12
![image](https://user-images.githubusercontent.com/51524384/236187993-9e1d19e8-e4ad-41a2-9d07-d4da19cb8593.png)


Please take a look at attached screenshot

**Comment by gildas-lormeau** [comment] 2023-05-04 13:09
The screenshot is not really useful unfortunately. I'm curious if the option change helps. If so, it confirms that it is a bug in the implementation of the `CompressionStream` API in Safari. I would not be surprised if it helps since someone already reported a similar issue in Safari, see https://www.construct.net/en/blogs/ashleys-blog-2/safari-releases-development-1616.

**Comment by gildas-lormeau** [comment] 2023-05-04 13:56
@AshleyScirra, was your issue similar to this one?

**Comment by AshleyScirra** [comment] 2023-05-04 14:36
I don't think it's https://bugs.webkit.org/show_bug.cgi?id=252474 since AFAIK the fix for that was shipped in 16.4. But who knows with Safari.

**Comment by gildas-lormeau** [comment] 2023-05-04 14:56
Thanks for your quick reply and the link, I see there is another bug (cf. https://bugs.webkit.org/show_bug.cgi?id=254021) opened on this API. That's not very reassuring. How did they manage to do this? :p

**Comment by Rajek88** [comment] 2023-05-04 19:12
> You should report this bug to Apple. Are you sure you're using the stable version of Safari? Also, do you confirm you don't see this bug in a Chromium-based browser?
> 
> Does setting the option `useCompressionStream` to `false` fix the issue?

Yes, tried by turning `useCompressionStream` to `false` and it worked!
Thank you so much @gildas-lormeau

**Comment by gildas-lormeau** [comment] 2023-05-04 19:43
You're welcome. I reported the bug here: https://bugs.webkit.org/show_bug.cgi?id=256330. Feel free to provide more info if you can. Ideally, it would be great if you could provide a zip file to reproduce the bug.

**Comment by gildas-lormeau** [comment] 2023-05-05 01:03
@Rajek88 Could you run again your code, set a breakpoint at line 3174 and test if `r < n.size` is `true` please?

**Comment by Rajek88** [comment] 2023-05-05 05:29
Sure, please allow me some time

**Comment by gildas-lormeau** [comment] 2023-05-05 09:23
@Rajek88 Forget my previous message, I found my answers in your screenshots. However, if you could provide a zip file to reproduce the issue, that would give some hopes that Apple find the bug.

**Comment by Rajek88** [comment] 2023-05-05 14:06
> @Rajek88 Forget my previous message, I found my answers in your screenshots. However, if you could provide a zip file to reproduce the issue, that would give some hope that Apple would find the bug.

Hi, @gildas-lormeau , I'm afraid, that as the zip contained some non-sharable information, I cannot share it, sorry for that, But yes, the zip file was about 1MB and was password protected.

**Comment by gildas-lormeau** [comment] 2023-05-05 20:24
@Rajek88 Do you know the software that was used to create the zip file maybe?

**Comment by gildas-lormeau** [comment] 2023-05-05 20:54
@Rajek88 Forget my request, I can reproduce the bug with the code below which is inspired from this thread on SO: https://stackoverflow.com/questions/67526864/how-to-inflate-a-gzip-with-a-really-old-zlib.

Steps to reproduce the issue:
- Open a new tab in Safari
- Open the developer tools
- Run the code below

```js
(async () => {
  const result = new TransformStream();
  (new Blob([new Uint8Array([0xec, 0x9a, 0x7f, 0x54, 0x1c, 0x55, 0x96, 0xc7, 0x6f, 0x75, 0x37, 0xd0, 0xfc, 0x70])]))
    .stream().pipeThrough(new DecompressionStream("deflate-raw")).pipeTo(result.writable);
  console.log(await new Response(result.readable).blob());
})();
```

Expected result:
An error similar to `TypeError: The input is ended without reaching the stream end` (Firefox) or `TypeError: Compressed input was truncated` (Chrome) should be thrown.

Result in Safari 16.4:
The error `TypeError: Extra bytes past the end.` is thrown instead.

**Comment by Rajek88** [comment] 2023-05-07 12:00
> @Rajek88 Do you know the software that was used to create the zip file maybe?

Hi, sorry for late reply, Missed the notification.
Sure, I was using android system to create zip files, 
You can find the documentation: https://developer.android.com/reference/java/util/zip/ZipEntry

**Comment by gildas-lormeau** [comment] 2023-05-09 00:17
I'm closing the issue because I do not expect new info and because it's not a bug in zip.js. Please post any info that could help to fix it here: https://bugs.webkit.org/show_bug.cgi?id=256330.

**Closed by gildas-lormeau** 2023-05-09 00:17 UTC
