### ISSUE TITLE
Corrupt zip file created using BlobReader on File object

### ISSUE THREAD

**Issue by tmccoid-tech** [gildas-lormeau/zip.js#508] opened 2024-04-22 21:06 UTC
Using the example provided at [https://github.com/gildas-lormeau/zip.js/blob/gh-pages/demos/demo-create-file.js](https://github.com/gildas-lormeau/zip.js/blob/gh-pages/demos/demo-create-file.js), I implemented a basic zip routine for use in an extension/add-on for the Mozilla Thunderbird email client.

The zip file is being generated without apparent error, and opening the archive in Windows File Explorer (or WinRAR, for that matter) displays the expected files.  However, these files are un-extractable, with WinRAR indicating a checksum error (file is corrupt) on any included file.

Here is an abstraction of the code I am using:

`async function add(fileName, fileData, creationDate) {`
`    const zipWriter =  new zip.ZipWriter(`
`         new zip.BlobWriter("application/zip"), { bufferedWrite: true, useCompressionStream: false }`
`    );`
`    await zipWriter.add(fileName, new zip.BlobReader(fileData),`
`        { creationDate: creationDate, useWebWorkers: false }`
`    );`
`    const result = await zipWriter.close();`
`    return result;`
`}`

The `fileData` parameter is a JavaScript File object.

I feel as if I must be missing something basic here.  Any guidance would be appreciated.

![Screenshot 2024-04-22 140444](https://github.com/gildas-lormeau/zip.js/assets/160653657/acc485e2-94f2-4dea-8a43-196e1c219de6)

**Comment by tmccoid-tech** [comment] 2024-04-23 00:14
One misconception I had is that compression would be off (level 0) by default; however, the default setting is 5.  I have discovered that setting it to 0 rectifies the problem, but am still uncertain as to why having the default (and perhaps any non-zero) compression level would result in archive corruption.  Is there a correlated option for either the BlobWriter or the `add` method of the ZipWriter object that needs to be set?  Thanks.

**Comment by gildas-lormeau** [comment] 2024-04-23 11:31
Thank you for the bug report. I think I was able to reproduce the issue. It looks like it happens only when importing `zip.js` built from the dist folder and when `useCompressionStream` and `useWebWorkers` are both set to `false`.

The tests below show the issue. The only difference is how `zip.s` is included.
- KO: https://plnkr.co/edit/LJAQcuL9Nc05tfjQ
- OK: https://plnkr.co/edit/aZVqOAXFjwwEywer

It's intriguing, I'll look into it.

**Comment by gildas-lormeau** [comment] 2024-04-23 11:45
I understand my mistake, I didn't include the good script. I have to include `<script src="https://unpkg.com/@zip.js/zip.js/dist/zip-full.js"></script>` in my case when not using web workers. By any chance, did you make the same mistake?

See https://plnkr.co/edit/p9K9N5c04YMlDBvS

**Comment by gildas-lormeau** [comment] 2024-04-23 12:01
It looks like you made the same mistake, see https://github.com/tmccoid-tech/extract-em/blob/main/module/zip.js.

I think it's still a bug in zip.js though. It should never create invalid zip files. Or it should at least warn the user. I'll look into how to avoid this.

**Comment by tmccoid-tech** [comment] 2024-04-23 14:19
Thanks for looking into this and providing a solution so quickly.

I wonder if you might want to update the demo I referenced in the first comment to use zip-full.js rather than zip.js, and maybe set the compression level explicitly and provide a comment to the effect of "0 = no compression, 5 = default, 9 = max" or the like.

**Comment by gildas-lormeau** [comment] 2024-04-23 14:55
The issue related to `zip-full.js` is fixed in the version `2.7.42`. Now, it will work for people who copy and paste from the demo code. For the record, the value from `1` to `9` of the `level` option is effective only when `useCompressionStream` is set to `false`. However, most of the time, the gain is negligible.

**Closed** 2024-04-23 15:01 UTC
