### ISSUE TITLE
Setting `compressionMethod` to 0 should have the same behavior as `level` to 0

### ISSUE THREAD

**Issue by cmcnicholas** [gildas-lormeau/zip.js#544] opened 2024-12-05 10:18 UTC
## Background

I am looking to create STORE only zip files on the client from a list of files held on our storage server.

The server supports range requests (we use these for other parts of our app e.g. streaming video chunks).

I believe I want to use `passthrough`, `HttpRangeReader` and `bufferedWrite` features of zip.js to make sure that files downloaded which are large don't consume large amounts of memory.

## Code

I have been trying to get pass through working with `HttpRangeReader`, my code looks like this:

```ts
import { HttpRangeReader, ZipWriter, configure } from '@zip.js/zip.js';

configure({ chunkSize: 5000 * 1024 });

export async function zipFile(files) {
  console.debug('zip_file', 'expanding_folders');

  const handle = await showSaveFilePicker({
    types: [
      {
        description: 'Zip file',
        accept: {
          'application/zip': ['.zip'],
        },
      },
    ],
    suggestedName: 'download.zip',
  });

  // create a writable stream to the file handle
  const writable: FileSystemWritableFileStream = await handle.createWritable({
    keepExistingData: false,
  });

  console.debug('zip_file', 'creating_zip_writer');

  // create a new zip writer
  const zipWriter = new ZipWriter(writable, {
    compressionMethod: 0,
    passThrough: true,
    bufferedWrite: true,
  });

  console.debug('zip_file', 'created_zip_writer');

  // download and add each file to the zip
  for (const file of files.fileSystems) {
    try {
      // add each file to the zip
      await zipWriter.add(file.name, new HttpRangeReader(file.readPresignedUrl), {
        uncompressedSize: file.size,
        async onprogress(progress, total) {
          console.log('onprogress: ' + file.name, progress, total);
        },
      });

      console.log('done file', file.name);
    } catch (e) {
      console.error('error', e);
      return;
    }
  }

  console.debug('zip_file', 'close_zip_started');

  try {
    // cleanup the zip
    await zipWriter.close(undefined, {
      async onprogress(progress, total) {
        console.log('onprogzip', progress, total);
      },
    });
  } catch (e) {
    console.error('zip_file', 'close_zip_error', e);
    return;
  }
}
```

To demonstrate what the "files" argument looks like, it is a response from our api e.g.

```ts
const files = {
  fileSystems: [
    {
      id: '67505eb8e6027ce99f65e09d',
      projectId: '66f1900a2d663a49bbbf4823',
      name: 'agent.png',
      size: 98159,
      readPresignedUrl:
        '<edited>',
      entityType: 'File',
      metadata: {
        // some metadata
      },
    },
```

## Problem

The code above creates the following zip file [github.zip](https://github.com/user-attachments/files/18021132/github.zip) and cannot be unpacked correctly.

7zip shows "CRC Failed"

## What I Have Tried

1. Remove `compressionMethod: 0, passThrough: true, bufferedWrite: true,` from `ZipWriter` AND `uncompressedSize`
Succeeds [1 NoAll.zip](https://github.com/user-attachments/files/18021219/1.NoAll.zip)

2. Setting only `compressionMethod = 8` from `ZipWriter`
Succeeds [2 Deflate.zip](https://github.com/user-attachments/files/18021223/2.Deflate.zip)

3. Setting `compressionMethod = 8 AND passThrough = true`
Error (undefined uncompressedSize) this was expected. [3 CompressAndPass.zip](https://github.com/user-attachments/files/18021224/3.CompressAndPass.zip)

4. Setting `compressionMethod = 8 AND passThrough = true` AND `uncompressedSize`
Fail (bad zip, 7zip reported CRC issue) [4 CompressAndPassAndSize.zip](https://github.com/user-attachments/files/18021229/4.CompressAndPassAndSize.zip)

5. Setting `compressionMethod = 8 AND bufferedWrite = true`
Success [5. Buffered.zip](https://github.com/user-attachments/files/18021234/5.Buffered.zip)

6. Setting `compressionMethod = 0 (store)`
Fail (bad zip, 7zip reported CRC issue) [6. NoCompress.zip](https://github.com/user-attachments/files/18021239/6.NoCompress.zip)

7. Setting `compressionMethod = 1`
Fail (bad zip, 7zip reported CRC issue) [7. Compress1.zip](https://github.com/user-attachments/files/18021246/7.Compress1.zip)

I must be doing something wrong here, but the code I have above is pretty straight forward (there is very little juggling going on).

**Comment by gildas-lormeau** [comment] 2024-12-05 10:35
This should be fine, zip.js relies entirely on Web Streams under-the-hood.

**Comment by cmcnicholas** [comment] 2024-12-05 10:46
Thanks again for responding so quickly, I have simplified the code above (removing passthrough and buffered write), I still seem to get an issue with compressionMethod = 0. If I leave the default, the zip is absolutely fine:

[compression-0.zip](https://github.com/user-attachments/files/18021827/compression-0.zip)
[compression-8.zip](https://github.com/user-attachments/files/18021828/compression-8.zip)

**Comment by gildas-lormeau** [comment] 2024-12-05 10:54
Could you try again without `uncompressedSize`? It's not needed.

**Comment by cmcnicholas** [comment] 2024-12-05 10:56
> Could you try again without `uncompressedSize`? It's not needed.

apologies I should have updated the code snippet, I have removed `uncompressedSize` see below:

```ts
import { HttpRangeReader, ZipWriter, configure } from '@zip.js/zip.js';

configure({ chunkSize: 5000 * 1024 });

export async function zipFile() {
  console.debug('zip_file', 'expanding_folders');

  const handle = await showSaveFilePicker({
    types: [
      {
        description: 'Zip file',
        accept: {
          'application/zip': ['.zip'],
        },
      },
    ],
    suggestedName: 'download.zip',
  });

  // create a writable stream to the file handle
  const writable: FileSystemWritableFileStream = await handle.createWritable({
    keepExistingData: false,
  });

  console.debug('zip_file', 'creating_zip_writer');

  // create a new zip writer
  const zipWriter = new ZipWriter(writable, {
    compressionMethod: 0, // works when set to 8 or not set at all
  });

  console.debug('zip_file', 'created_zip_writer');

  // download and add each file to the zip
  for (const file of files.fileSystems) {
    try {
      // add each file to the zip
      await zipWriter.add(file.name, new HttpRangeReader(file.readPresignedUrl), {
        async onprogress(progress, total) {
          console.log('onprogress: ' + file.name, progress, total);
        },
      });

      console.log('done file', file.name);
    } catch (e) {
      console.error('error', e);
      return;
    }
  }

  console.debug('zip_file', 'close_zip_started');

  try {
    // cleanup the zip
    await zipWriter.close(undefined, {
      async onprogress(progress, total) {
        console.log('onprogzip', progress, total);
      },
    });
  } catch (e) {
    console.error('zip_file', 'close_zip_error', e);
    return;
  }
}

const files = {
  fileSystems: [
    {
      id: '67505eb8e6027ce99f65e09d',
      projectId: '66f1900a2d663a49bbbf4823',
      name: 'agent.png',
      size: 98159,
      readPresignedUrl:
        'https://engage-dev-london.s3.eu-west-1.wasabisys.com/67505eb8e6027ce99f65e09d/agent.png?X-Amz-Expires=86400&response-content-disposition=inline&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=T9GEDPIY38YWZUMFN8WP%2F20241204%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20241204T174012Z&X-Amz-SignedHeaders=host&X-Amz-Signature=821c48676366851ca9aea619f78e504bedfcaf6b8517d2a2b04739ed9134353d',
      entityType: 'File',
      metadata: {
        // metadata
      },
    },
  ],
};

```

**Comment by gildas-lormeau** [comment] 2024-12-05 10:59
Thank you, actually it's probably due to the fact that you should set `level` to `0` instead of `compressionMethod` to `0`.

**Comment by cmcnicholas** [comment] 2024-12-05 11:03
> Thank you, actually it's probably due to the fact that you should set `level` to `0` instead of `compressionMethod` to `0`.

amazing, thank you for that, I can confirm I'm getting the desired outputs now :)

**Comment by gildas-lormeau** [comment] 2024-12-05 11:07
I'm glad to hear it! Because setting `compressionMethod` to `0` should work (and have the same behavior as `level` to `0`), I'll leave the issue open.

**Comment by cmcnicholas** [comment] 2024-12-05 11:15
> I'm glad to hear it! Because setting `compressionMethod` to `0` should work (and have the same behavior as `level` to `0`), I'll leave the issue open.

you need a donations button mate so I can buy you a coffee XD

**Comment by gildas-lormeau** [comment] 2024-12-05 11:18
Thank you! Actually, there are donation links here https://github.com/gildas-lormeau/SingleFile ;)

**Comment by gildas-lormeau** [comment] 2024-12-05 11:23
Thank you very much!

**Comment by gildas-lormeau** [comment] 2024-12-05 15:06
The issue is fixed on `master`.

**Closed by gildas-lormeau** 2024-12-05 15:06 UTC
