### ISSUE TITLE
Support UTF-8 filename

### ISSUE THREAD

**Issue by danny0838** [gildas-lormeau/zip.js#176] opened 2017-06-26 17:23 UTC
1. On a OS not using UTF-8 filename en oding, create a zip file by zip.js with a file containing non-ASCII chars.
2. Transfer the file to an OS using UTF-8, and then unzip it.
3. The non-ASCII filenames are garbled.

It would be nice to set the EFS (see [spec](https://www.pkware.com/documents/casestudies/APPNOTE.TXT)) for files added to the zip so that the filename won't be garbled among filesystems using different encodings.

**Comment by greggman** [comment] 2017-12-31 03:24
Isn't this the same as #131

**Comment by gildas-lormeau** [comment] 2021-01-12 11:38
duplicate of https://github.com/gildas-lormeau/zip.js/issues/131

**Closed by gildas-lormeau** 2021-01-12 11:38 UTC
